/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ThreatGraphRouteImport } from './routes/threat-graph'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatGraphRoute = ThreatGraphRouteImport.update({
  id: '/threat-graph',
  path: '/threat-graph',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/evidence': typeof EvidenceRoute
  '/integrations': typeof IntegrationsRoute
  '/investigations': typeof InvestigationsRoute
  '/login': typeof LoginRoute
  '/playbooks': typeof PlaybooksRoute
  '/policies': typeof PoliciesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/threat-graph': typeof ThreatGraphRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/evidence': typeof EvidenceRoute
  '/integrations': typeof IntegrationsRoute
  '/investigations': typeof InvestigationsRoute
  '/login': typeof LoginRoute
  '/playbooks': typeof PlaybooksRoute
  '/policies': typeof PoliciesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/threat-graph': typeof ThreatGraphRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/evidence': typeof EvidenceRoute
  '/integrations': typeof IntegrationsRoute
  '/investigations': typeof InvestigationsRoute
  '/login': typeof LoginRoute
  '/playbooks': typeof PlaybooksRoute
  '/policies': typeof PoliciesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/threat-graph': typeof ThreatGraphRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/evidence'
    | '/integrations'
    | '/investigations'
    | '/login'
    | '/playbooks'
    | '/policies'
    | '/reports'
    | '/settings'
    | '/threat-graph'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/evidence'
    | '/integrations'
    | '/investigations'
    | '/login'
    | '/playbooks'
    | '/policies'
    | '/reports'
    | '/settings'
    | '/threat-graph'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/evidence'
    | '/integrations'
    | '/investigations'
    | '/login'
    | '/playbooks'
    | '/policies'
    | '/reports'
    | '/settings'
    | '/threat-graph'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  EvidenceRoute: typeof EvidenceRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InvestigationsRoute: typeof InvestigationsRoute
  LoginRoute: typeof LoginRoute
  PlaybooksRoute: typeof PlaybooksRoute
  PoliciesRoute: typeof PoliciesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ThreatGraphRoute: typeof ThreatGraphRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-graph': {
      id: '/threat-graph'
      path: '/threat-graph'
      fullPath: '/threat-graph'
      preLoaderRoute: typeof ThreatGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  EvidenceRoute: EvidenceRoute,
  IntegrationsRoute: IntegrationsRoute,
  InvestigationsRoute: InvestigationsRoute,
  LoginRoute: LoginRoute,
  PlaybooksRoute: PlaybooksRoute,
  PoliciesRoute: PoliciesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ThreatGraphRoute: ThreatGraphRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
